# Site settings
title: Ravers
description: "When a raver goes to a rave party, they are carrying much more than their ticket and their wallets. When one thinks about ravers and the rave scene, the first thought that comes to mind is often related to drug use."
url: "http://ravers.com/"
#author:
#  name: "Chethan Bhat"
#  email: "hello@chethanbhat.com"
#  url: "http://chethanbhat.com"

# Build settings

baseurl: "/ravers" #Change during final commit to github
url: "https://chethanbhat.github.io/ravers/"
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
